using UnityEngine;
using UnityEditor;
using System.Text;
using System.IO;
using System.Collections;

public class MTSceneMenuGenerator : Editor {
	
	private static string openerPath = "/Editor/MTSceneMenu.cs";
	
	[MenuItem("Scenes/UpdateScenes", false, 100)]
	private static void UpdateScenes()
	{
		string filePath = Application.dataPath + openerPath;
		
		StreamWriter sr = File.CreateText(filePath);
		
		sr.WriteLine(
			@"
//this class was auto generated by MTSceneMenuGenerator.cs
using UnityEditor;
using System.Collections;

public class MTSceneMenuOpener{");
		
		foreach (var s in EditorBuildSettings.scenes) {
			sr.WriteLine(GetMethodStr(s.path));
		}
		
		sr.WriteLine("}");
		
		sr.Close();
		
		AssetDatabase.Refresh();
		
	}
	
	private static string GetMethodStr(string scenePath)
	{
		string sceneName = Path.GetFileName(scenePath).Replace(".unity","");
		
		string baseStr = 
			"[MenuItem(\"Scenes/sceneName\")] " +
				"private static void sceneName() " +
				"{ " +
				"EditorApplication.OpenScene(\"scenePath\"); " +
				"}";
		
		baseStr = baseStr.Replace("sceneName",sceneName);
		baseStr = baseStr.Replace("scenePath", scenePath);
		
		return baseStr;
	}
	
}
